version: '3.8'

services:
  backend:
      build: ./material-applications/example-backend
      image: backend-project
      ports:
        - "8080:8080"
  frontend:
      build: ./material-applications/example-frontend
      image: frontend-project
      ports:
        - "5000:5000"
