version: '3.8'

services:
  redis:
      image: redis
  backend:
      build: ./material-applications/example-backend
      image: backend-project
      ports:
        - "8080:8080"
      environment:
        - REDIS_HOST=redis
  frontend:
      build: ./material-applications/example-frontend
      image: frontend-project
      ports:
        - "5000:5000"
