version: '3.8'

services:
  nginx:
    image: nginx:1.23.3-alpine
    networks:
      - proxy-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    networks:
      - db-network
    environment:
      POSTGRES_PASSWORD: example
    container_name: postgres
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
  redis:
      image: redis
      networks:
        - db-network
  backend:
      build: ./material-applications/example-backend
      image: backend-project
      networks:
        - proxy-network
        - db-network
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres
        - POSTGRES_PASSWORD=example
        - DB_HOST=postgres
        - REQUEST_ORIGIN=http://localhost
      container_name: backend
  frontend:
      build: ./material-applications/example-frontend
      image: frontend-project
      networks:
        - proxy-network
      environment:
        - REACT_APP_BACKEND_URL=http://localhost/api
      container_name: frontend
networks:
  db-network:
  proxy-network:
volumes:
  postgres:
  nginx:

