version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    ports:
      - "5000:8080"
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
  express-app:
    image: muggs/express-app:latest
    ports:
      - "8080:8080"
    container_name: express
